package com.lingke.xvp.demo.db.dao;

import com.lingke.xvp.demo.db.dao.base.BaseSeller;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Seller extends BaseSeller<Seller> {
	
}
